//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSK.ClientApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POSK.ClientApp.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with card.
        /// </summary>
        internal static string ATM {
            get {
                return ResourceManager.GetString("ATM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM card payment.
        /// </summary>
        internal static string CARD_READER_WORKING {
            get {
                return ResourceManager.GetString("CARD_READER_WORKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay in cash.
        /// </summary>
        internal static string CASH {
            get {
                return ResourceManager.GetString("CASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash payment.
        /// </summary>
        internal static string CASH_CODE_WORKING {
            get {
                return ResourceManager.GetString("CASH_CODE_WORKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        internal static string CONTINUE_SHOPPING {
            get {
                return ResourceManager.GetString("CONTINUE_SHOPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string EXTEND_SESSION {
            get {
                return ResourceManager.GetString("EXTEND_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string FINISH_NOW {
            get {
                return ResourceManager.GetString("FINISH_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The allowed payment methods :.
        /// </summary>
        internal static string ONLY_THOSE_ARE_WORKING {
            get {
                return ResourceManager.GetString("ONLY_THOSE_ARE_WORKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckOut.
        /// </summary>
        internal static string PAY_ORDER {
            get {
                return ResourceManager.GetString("PAY_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to note : printer is not working.
        /// </summary>
        internal static string PRINTER_WORKING {
            get {
                return ResourceManager.GetString("PRINTER_WORKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string PRODUCT_TYPE_DATA {
            get {
                return ResourceManager.GetString("PRODUCT_TYPE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice.
        /// </summary>
        internal static string PRODUCT_TYPE_VOICE {
            get {
                return ResourceManager.GetString("PRODUCT_TYPE_VOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Pins.
        /// </summary>
        internal static string RECEIVE_ORDER {
            get {
                return ResourceManager.GetString("RECEIVE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining : .
        /// </summary>
        internal static string REMAINING {
            get {
                return ResourceManager.GetString("REMAINING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string RETURN {
            get {
                return ResourceManager.GetString("RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, Select payment method.
        /// </summary>
        internal static string SELECT_PAYMENT {
            get {
                return ResourceManager.GetString("SELECT_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired.
        /// </summary>
        internal static string SESSION_EXPIRED {
            get {
                return ResourceManager.GetString("SESSION_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired, Please receive the receipt.
        /// </summary>
        internal static string SESSION_EXPIRED_WITH_VALUE {
            get {
                return ResourceManager.GetString("SESSION_EXPIRED_WITH_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold.
        /// </summary>
        internal static string SOLD {
            get {
                return ResourceManager.GetString("SOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry !!!.
        /// </summary>
        internal static string SORRY {
            get {
                return ResourceManager.GetString("SORRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMINAL IS DISABLED.
        /// </summary>
        internal static string TERMINAL_IS_DISABLED {
            get {
                return ResourceManager.GetString("TERMINAL_IS_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You, Please receive the receipt..
        /// </summary>
        internal static string THANK_YOU {
            get {
                return ResourceManager.GetString("THANK_YOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid : .
        /// </summary>
        internal static string TOTAL_PAID {
            get {
                return ResourceManager.GetString("TOTAL_PAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand : .
        /// </summary>
        internal static string TOTAL_VALUE {
            get {
                return ResourceManager.GetString("TOTAL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
